# Generated by Django 3.2.7 on 2021-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_to_image',
            field=models.URLField(default='', max_length=350),
        ),
    ]
