# Generated by Django 3.2.7 on 2021-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.webp', upload_to='product_images/'),
        ),
    ]
