# Generated by Django 3.2.7 on 2021-11-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0003_alter_product_link_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link_to_image',
            field=models.URLField(default='', max_length=350),
        ),
    ]
